In [1]:
from bs4 import BeautifulSoup
import urllib.request as urlib
import pandas as pd
import numpy as np

# Sydney

In [2]:
# define all postal codes 
input_file = pd.read_csv('sydney_postalcodes.csv', header=None)
postalcode = input_file.as_matrix()
print(postalcode.shape)
# define years 
years = ["2006", "2011", "2016"]
database = []

(198, 1)


In [4]:
i = 0
for year in years: 
    print("Year:" , year)
    database.append([])
    i+=1
    for pc in postalcode: 
        pc = pc[0]
        site = "http://www.censusdata.abs.gov.au/census_services/getproduct/census/"+year+"/quickstat/POA"+str(pc)
        page = urlib.urlopen(site)
        soup = BeautifulSoup(page)
        if(year != "2016"):
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cells = row.find_all('td')
                    if("Median incomes" in str(cells[0])):
                        c = cells[1].string
                        c = c[1:]
                        c = c.replace(',', '')
                        nr = int(c)
                        database[i-1].append(nr)
                        print("    PC ", pc)
        else: 
            cells = []
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cell = row.find_all('td')
                    cells.append(cell[0])
            if(len(cells) != 1):
                c = cells[10].string
                c = c[1:]
                c = c.replace(',', '')
                nr = int(c)
                database[i-1].append(nr)
                print("pc", pc)
            else:
                print("pc: ", pc, "Error")

Year: 2006


/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


    PC  2107
    PC  2106
    PC  2103
    PC  2104
    PC  2102
    PC  2105
    PC  2101
    PC  2084
    PC  2097
    PC  2074
    PC  2075
    PC  2085
    PC  2100
    PC  2099
    PC  2120
    PC  2121
    PC  2122
    PC  2073
    PC  2072
    PC  2071
    PC  2086
    PC  2087
    PC  2092
    PC  2093
    PC  2096
    PC  2076
    PC  2077
    PC  2126
    PC  2125
    PC  2119
    PC  2118
    PC  2117
    PC  2114
    PC  2112
    PC  2113
    PC  2109
    PC  2070
    PC  2069
    PC  2094
    PC  2095
    PC  2079
    PC  2154
    PC  2153
    PC  2151
    PC  2150
    PC  2116
    PC  2115
    PC  2111
    PC  2066
    PC  2110
    PC  2067
    PC  2068
    PC  2155
    PC  2768
    PC  2147
    PC  2146
    PC  2152
    PC  2145
    PC  2160
    PC  2142
    PC  2128
    PC  2127
    PC  2064
    PC  2065
    PC  2063
    PC  2763
    PC  2148
    PC  2164
    PC  2161
    PC  2162
    PC  2144
    PC  2141
    PC  2140
    PC  2138
    PC  2060
    PC  2062
    PC  2761

In [5]:
print(database)
print(len(database[0]))
print(len(database[1]))
print(len(database[2]))

[[1562, 1453, 1263, 1310, 1620, 1980, 1271, 1634, 1492, 1884, 2201, 1688, 1401, 1162, 1670, 1458, 1157, 2397, 1940, 2220, 1733, 1551, 2088, 1562, 1517, 1884, 1195, 1861, 2090, 2075, 1339, 1077, 1136, 1159, 1170, 785, 2088, 2172, 1680, 1591, 1602, 1715, 1599, 1161, 998, 1075, 1046, 1332, 1698, 1884, 1415, 1737, 1875, 1694, 1115, 1108, 1286, 1068, 861, 811, 910, 1701, 1556, 1823, 2387, 1436, 1029, 992, 807, 811, 736, 941, 1075, 1564, 1763, 1799, 1224, 1139, 1154, 763, 603, 801, 852, 860, 823, 1151, 1490, 1811, 1757, 1793, 786, 1408, 974, 698, 1176, 796, 851, 692, 1106, 1006, 1435, 1903, 885, 1089, 1002, 899, 1406, 1022, 1080, 977, 983, 1042, 804, 933, 1046, 1171, 1726, 1291, 1072, 1068, 1139, 2027, 1127, 1823, 1186, 1046, 1006, 1077, 1121, 778, 1119, 1041, 1161, 1490, 1112, 868, 1267, 1444, 1300, 1057, 1036, 1036, 1056, 1050, 1121, 1210, 1673, 2093, 1200, 1416, 1231, 1698, 1031, 1109, 1209, 1340, 1442, 1565, 1121, 1935, 525, 1131, 1243, 1197, 977, 1697, 1653, 1147, 938, 1736, 1190, 1025,

In [7]:
bla = database
bla2 = database


In [16]:
print(database)

[[1562, 1453, 1263, 1310, 1620, 1980, 1271, 1634, 1492, 1884, 2201, 1688, 1401, 1162, 1670, 1458, 1157, 2397, 1940, 2220, 1733, 1551, 2088, 1562, 1517, 1884, 1195, 1861, 2090, 2075, 1339, 1077, 1136, 1159, 1170, 785, 2088, 2172, 1680, 1591, 1602, 1715, 1599, 1161, 998, 1075, 1046, 1332, 1698, 1884, 1415, 1737, 1875, 1694, 1115, 1108, 1286, 1068, 861, 811, 910, 1701, 1556, 1823, 2387, 1436, 1029, 992, 807, 811, 736, 941, 1075, 1564, 1763, 1799, 1224, 1139, 1154, 763, 603, 801, 852, 860, 823, 1151, 1490, 1811, 1757, 1793, 786, 1408, 974, 698, 1176, 796, 851, 692, 1106, 1006, 1435, 1903, 885, 1089, 1002, 899, 1406, 1022, 1080, 977, 983, 1042, 804, 933, 1046, 1171, 1726, 1291, 1072, 1068, 1139, 2027, 1127, 1823, 1186, 1046, 1006, 1077, 1121, 778, 1119, 1041, 1161, 1490, 1112, 868, 1267, 1444, 1300, 1057, 1036, 1036, 1056, 1050, 1121, 1210, 1673, 2093, 1200, 1416, 1231, 1698, 1031, 1109, 1209, 1340, 1442, 1565, 1121, 1935, 525, 1131, 1243, 1197, 977, 1697, 1653, 1147, 938, 1736, 1190, 1025,

In [17]:
for i in range(3):
    while(len(database[i]) <= 198):
        database[i].append(0)
    print(len(database[i]))
db = np.zeros((199,3), np.int32)
db[:,0] = database[0]
db[:, 1] = database[1]
db[:, 2] = database[2]

199
199
199


In [19]:
print(db[0])
df = pd.DataFrame(db)
df.to_csv("sydney_income.csv")

[1562 1887 2250]


# Melbourne

In [7]:
# define all postal codes 
input_file = pd.read_csv('melbourne_postal_code.csv', header=None)
postalcode = input_file.as_matrix()
postalcode = postalcode[1:]
print(postalcode.shape)
# define years 
years = ["2006", "2011", "2016"]
database = []

(178, 1)


In [8]:
i = 0
for year in years: 
    print("Year:" , year)
    database.append([])
    i+=1
    for pc in postalcode: 
        pc = pc[0]
        site = "http://www.censusdata.abs.gov.au/census_services/getproduct/census/"+year+"/quickstat/POA"+str(pc)
        page = urlib.urlopen(site)
        soup = BeautifulSoup(page)
        if(year != "2016"):
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cells = row.find_all('td')
                    if("Median incomes" in str(cells[0])):
                        c = cells[1].string
                        c = c[1:]
                        c = c.replace(',', '')
                        nr = int(c)
                        database[i-1].append(nr)
                        print("    PC ", pc)
        else: 
            cells = []
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cell = row.find_all('td')
                    cells.append(cell[0])
            if(len(cells) != 1):
                c = cells[10].string
                c = c[1:]
                c = c.replace(',', '')
                nr = int(c)
                database[i-1].append(nr)
                print("pc", pc)
            else:
                print("pc: ", pc, "Error")

Year: 2006


/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


    PC  3944
    PC  3943
    PC  3942
    PC  3941
    PC  3939
    PC  3940
    PC  3938
    PC  3936
    PC  3934
    PC  3915
    PC  3931
    PC  3913
    PC  3918
    PC  3930
    PC  3912
    PC  3919
    PC  3920
    PC  3911
    PC  3199
    PC  3910
    PC  3200
    PC  3198
    PC  3201
    PC  3197
    PC  3175
    PC  3196
    PC  3195
    PC  3173
    PC  3174
    PC  3170
    PC  3172
    PC  3194
    PC  3171
    PC  3168
    PC  3150
    PC  3202
    PC  3169
    PC  3193
    PC  3192
    PC  3167
    PC  3166
    PC  3149
    PC  3133
    PC  3151
    PC  3189
    PC  3191
    PC  3190
    PC  3165
    PC  3163
    PC  3148
    PC  3147
    PC  3125
    PC  3131
    PC  3132
    PC  3130
    PC  3188
    PC  3204
    PC  3183
    PC  3162
    PC  3145
    PC  3146
    PC  3124
    PC  3127
    PC  3128
    PC  3111
    PC  3129
    PC  3109
    PC  3186
    PC  3187
    PC  3184
    PC  3182
    PC  3181
    PC  3161
    PC  3185
    PC  3144
    PC  3123
    PC  3126

In [11]:
print(database)
print(len(database[0]))
print(len(database[1]))
print(len(database[2]))

[[1221, 1435, 1209, 1443, 1443, 1140, 1049, 877, 1228, 1102, 1196, 1193, 1033, 1063, 1116, 1187, 1520, 1197, 1090, 1017, 1131, 1102, 1290, 1181, 1054, 1115, 1050, 1028, 1204, 1643, 1821, 1003, 1663, 1459, 937, 1671, 1551, 1181, 1137, 1073, 1349, 1160, 910], [1746, 1997, 1597, 2081, 1868, 1619, 1475, 1243, 2937, 1639, 1315, 1669, 1487, 1400, 1365, 1522, 1767, 2210, 1805, 1458, 1276, 1474, 1465, 1719, 1674, 1363, 1418, 1329, 1046, 1652, 2142, 2347, 1342, 2261, 1862, 1160, 2286, 1938, 1688, 1618, 1495, 1779, 1616, 1071], [1728, 2190, 1634, 2289, 1618, 2054, 1728, 1489, 1499, 1730, 1385, 1779, 1665, 1613, 1671, 1789, 2065, 2392, 2030, 1669, 1467, 1643, 1709, 1959, 2031, 1676, 1594, 1489, 1375, 1946, 2254, 2403, 1628, 2486, 2094, 1299, 2538, 2163, 1895, 1834, 1724, 1918, 1828, 1199]]
43
44
44


In [10]:
bla = database
bla2 = database


In [13]:
for i in range(3):
    while(len(database[i]) <= 178):
        database[i].append(0)
    print(len(database[i]))
db = np.zeros((179,3), np.int32)
db[:,0] = database[0]
db[:, 1] = database[1]
db[:, 2] = database[2]

179
179
179


In [14]:
print(db[0])
df = pd.DataFrame(db)
df.to_csv("melbourne_income.csv")

[1300 1874 1863]


# Brisbane

In [9]:
# define all postal codes 
input_file = pd.read_csv('brisbane_postalcodes.csv', header=None)
postalcode = input_file.as_matrix()
print(postalcode.shape)
# define years 
years = ["2006", "2011", "2016"]
database = []

(46, 1)


In [10]:
i = 0
for year in years: 
    print("Year:" , year)
    database.append([])
    i+=1
    for pc in postalcode: 
        pc = pc[0]
        site = "http://www.censusdata.abs.gov.au/census_services/getproduct/census/"+year+"/quickstat/POA"+str(pc)
        page = urlib.urlopen(site)
        soup = BeautifulSoup(page)
        if(year != "2016"):
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cells = row.find_all('td')
                    if("Median incomes" in str(cells[0])):
                        c = cells[1].string
                        c = c[1:]
                        c = c.replace(',', '')
                        nr = int(c)
                        database[i-1].append(nr)
                        print("    PC ", pc)
        else: 
            cells = []
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cell = row.find_all('td')
                    cells.append(cell[0])
            if(len(cells) != 1):
                if(len(cells)>=10):
                    c = cells[10].string
                    c = c[1:]
                    c = c.replace(',', '')
                    nr = int(c)
                    database[i-1].append(nr)
                    print("pc", pc)
            else:
                print("pc: ", pc, "Error")

Year: 2006


/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


    PC  4000
    PC  4064
    PC  4059
    PC  4060
    PC  4006
    PC  4005
    PC  4101
    PC  4102
    PC  4068
    PC  4067
    PC  4066
    PC  4104
    PC  4103
    PC  4120
    PC  4151
    PC  4170
    PC  4171
    PC  4172
    PC  4174
    PC  4178
    PC  4173
    PC  4179
    PC  4152
    PC  4121
    PC  4105
    PC  4122
    PC  4111
    PC  4106
    PC  4075
    PC  4073
    PC  4069
    PC  4107
    PC  4154
    PC  4153
    PC  4158
    PC  4065
    PC  4061
    PC  4051
    PC  4030
    PC  4010
    PC  4007
    PC  4011
    PC  4008
Year: 2011
    PC  4000
    PC  4064
    PC  4059
    PC  4060
    PC  4006
    PC  4005
    PC  4101
    PC  4102
    PC  4072
    PC  4068
    PC  4067
    PC  4066
    PC  4104
    PC  4103
    PC  4120
    PC  4151
    PC  4170
    PC  4171
    PC  4172
    PC  4174
    PC  4178
    PC  4173
    PC  4179
    PC  4152
    PC  4121
    PC  4105
    PC  4122
    PC  4111
    PC  4106
    PC  4075
    PC  4073
    PC  4069
    PC  4107
 

In [12]:
print(database)
print(len(database[0]))
print(len(database[1]))
print(len(database[2]))
bla = database

[[1221, 1435, 1209, 1443, 1443, 1140, 1049, 877, 1228, 1102, 1196, 1193, 1033, 1063, 1116, 1187, 1520, 1197, 1090, 1017, 1131, 1102, 1290, 1181, 1054, 1115, 1050, 1028, 1204, 1643, 1821, 1003, 1663, 1459, 937, 1671, 1551, 1181, 1137, 1073, 1349, 1160, 910], [1746, 1997, 1597, 2081, 1868, 1619, 1475, 1243, 2937, 1639, 1315, 1669, 1487, 1400, 1365, 1522, 1767, 2210, 1805, 1458, 1276, 1474, 1465, 1719, 1674, 1363, 1418, 1329, 1046, 1652, 2142, 2347, 1342, 2261, 1862, 1160, 2286, 1938, 1688, 1618, 1495, 1779, 1616, 1071], [1728, 2190, 1634, 2289, 1618, 2054, 1728, 1489, 1499, 1730, 1385, 1779, 1665, 1613, 1671, 1789, 2065, 2392, 2030, 1669, 1467, 1643, 1709, 1959, 2031, 1676, 1594, 1489, 1375, 1946, 2254, 2403, 1628, 2486, 2094, 1299, 2538, 2163, 1895, 1834, 1724, 1918, 1828, 1199]]
43
44
44


In [13]:
for i in range(3):
    while(len(database[i]) <= 46):
        database[i].append(0)
    print(len(database[i]))
db = np.zeros((47,3), np.int32)
db[:,0] = database[0]
db[:, 1] = database[1]
db[:, 2] = database[2]

47
47
47


In [15]:
print(db[0])
df = pd.DataFrame(db)
df.to_csv("brisbane_income.csv")

[1221 1746 1728]


# Perth

In [22]:
# define all postal codes 
input_file = pd.read_csv('perth_postalcode.csv', header=None)
postalcode = input_file.as_matrix()
print(postalcode.shape)
# define years 
years = ["2006", "2011", "2016"]
database = []
print(postalcode)

(52, 1)
[[6012]
 [6005]
 [6004]
 [6003]
 [6011]
 [6010]
 [6009]
 [6007]
 [6000]
 [6008]
 [6014]
 [6015]
 [6016]
 [6006]
 [6050]
 [6051]
 [6052]
 [6060]
 [6104]
 [6103]
 [6100]
 [6101]
 [6106]
 [6105]
 [6102]
 [6152]
 [6151]
 [6153]
 [6154]
 [6156]
 [6157]
 [6158]
 [6159]
 [6160]
 [6162]
 [6163]
 [6150]
 [6149]
 [6155]
 [6108]
 [6147]
 [6164]
 [6166]
 [6110]
 [6109]
 [6148]
 [6107]
 [6058]
 [6057]
 [6017]
 [6053]
 [6054]]


In [17]:
i = 0
for year in years: 
    print("Year:" , year)
    database.append([])
    i+=1
    for pc in postalcode: 
        pc = pc[0]
        site = "http://www.censusdata.abs.gov.au/census_services/getproduct/census/"+year+"/quickstat/POA"+str(pc)
        page = urlib.urlopen(site)
        soup = BeautifulSoup(page)
        if(year != "2016"):
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cells = row.find_all('td')
                    if("Median incomes" in str(cells[0])):
                        c = cells[1].string
                        c = c[1:]
                        c = c.replace(',', '')
                        nr = int(c)
                        database[i-1].append(nr)
                        print("    PC ", pc)
        else: 
            cells = []
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cell = row.find_all('td')
                    cells.append(cell[0])
            if(len(cells) != 1):
                if(len(cells)>=10):
                    c = cells[10].string
                    c = c[1:]
                    c = c.replace(',', '')
                    nr = int(c)
                    database[i-1].append(nr)
                    print("pc", pc)
            else:
                print("pc: ", pc, "Error")

Year: 2006


/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


    PC  6012
    PC  6005
    PC  6004
    PC  6003
    PC  6011
    PC  6010
    PC  6009
    PC  6007
    PC  6000
    PC  6008
    PC  6014
    PC  6015
    PC  6016
    PC  6006
    PC  6050
    PC  6051
    PC  6052
    PC  6060
    PC  6104
    PC  6103
    PC  6100
    PC  6101
    PC  6105
    PC  6102
    PC  6152
    PC  6151
    PC  6153
    PC  6154
    PC  6156
    PC  6157
    PC  6158
    PC  6159
    PC  6160
    PC  6162
    PC  6163
    PC  6150
    PC  6149
    PC  6155
    PC  6108
    PC  6147
    PC  6164
    PC  6166
    PC  6110
    PC  6109
    PC  6148
    PC  6107
    PC  6058
    PC  6057
    PC  6017
    PC  6053
    PC  6054
Year: 2011
    PC  6012
    PC  6005
    PC  6004
    PC  6003
    PC  6011
    PC  6010
    PC  6009
    PC  6007
    PC  6000
    PC  6008
    PC  6014
    PC  6015
    PC  6016
    PC  6006
    PC  6050
    PC  6051
    PC  6052
    PC  6060
    PC  6104
    PC  6103
    PC  6100
    PC  6101
    PC  6106
    PC  6105
    PC  6102
 

In [18]:
print(database)
print(len(database[0]))
print(len(database[1]))
print(len(database[2]))
bla = database

[[1073, 1072, 1106, 923, 1907, 1342, 1506, 1269, 1072, 1426, 1183, 1888, 1063, 1138, 1129, 807, 1085, 859, 955, 781, 1018, 968, 861, 620, 1069, 1209, 1294, 1068, 1080, 1000, 1265, 1316, 948, 910, 933, 1440, 1442, 1460, 1100, 957, 1278, 1165, 996, 833, 1091, 935, 1057, 1157, 728, 1018, 925], [1497, 1699, 1814, 1385, 2519, 1843, 2217, 1927, 1750, 1889, 1759, 2576, 1579, 1736, 1715, 1221, 1489, 1199, 1357, 1293, 1514, 1385, 4500, 1168, 875, 1452, 1842, 1832, 1440, 1486, 1412, 1838, 1861, 1397, 1195, 1195, 1783, 1884, 1917, 1411, 1235, 1850, 1550, 1285, 1093, 1454, 1300, 1304, 1552, 1102, 1413, 1214], [1864, 1736, 1868, 1765, 2782, 2170, 2306, 2163, 1827, 2107, 2021, 2925, 1957, 2074, 1894, 1449, 1805, 1420, 1511, 1456, 1679, 1616, 0, 1349, 1050, 1662, 1952, 2055, 1721, 1795, 1635, 2051, 2173, 1548, 1533, 1424, 1968, 1950, 2007, 1449, 1352, 1987, 1864, 1452, 1199, 1596, 1469, 1459, 1635, 1207, 1705, 1415]]
51
52
52


In [19]:
for i in range(3):
    while(len(database[i]) <= 52):
        database[i].append(0)
    print(len(database[i]))
db = np.zeros((53,3), np.int32)
db[:,0] = database[0]
db[:, 1] = database[1]
db[:, 2] = database[2]

53
53
53


In [20]:
print(db[0])
df = pd.DataFrame(db)
df.to_csv("perth_income.csv")

[1073 1497 1864]


# Adelaide

In [2]:
# define all postal codes 
input_file = pd.read_csv('adelaide_postalcodes.csv', header=None)
postalcode = input_file.as_matrix()
print(postalcode.shape)
# define years 
years = ["2006", "2011", "2016"]
database = []

(52, 1)


In [3]:
i = 0
for year in years: 
    print("Year:" , year)
    database.append([])
    i+=1
    for pc in postalcode: 
        pc = pc[0]
        site = "http://www.censusdata.abs.gov.au/census_services/getproduct/census/"+year+"/quickstat/POA"+str(pc)
        page = urlib.urlopen(site)
        soup = BeautifulSoup(page)
        if(year != "2016"):
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cells = row.find_all('td')
                    if("Median incomes" in str(cells[0])):
                        c = cells[1].string
                        c = c[1:]
                        c = c.replace(',', '')
                        nr = int(c)
                        database[i-1].append(nr)
                        print("    PC ", pc)
        else: 
            cells = []
            table = soup.find_all('table', class_='summaryTable')
            for table in table: 
                tr = table.find_all('tr')
                for row in tr:
                    cell = row.find_all('td')
                    cells.append(cell[0])
            if(len(cells) != 1):
                if(len(cells)>=10):
                    c = cells[10].string
                    c = c[1:]
                    c = c.replace(',', '')
                    nr = int(c)
                    database[i-1].append(nr)
                    print("pc", pc)
            else:
                print("pc: ", pc, "Error")

Year: 2006


/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


    PC  5000
    PC  5006
    PC  5031
    PC  5033
    PC  5034
    PC  5061
    PC  5063
    PC  5065
    PC  5067
    PC  5069
    PC  5081
    PC  5083
    PC  5082
    PC  5007
    PC  5008
    PC  5009
    PC  5025
    PC  5032
    PC  5022
    PC  5023
    PC  5024
    PC  5037
    PC  5040
    PC  5045
    PC  5038
    PC  5044
    PC  5048
    PC  5043
    PC  5042
    PC  5041
    PC  5062
    PC  5039
    PC  5064
    PC  5066
    PC  5068
    PC  5072
    PC  5073
    PC  5070
    PC  5074
    PC  5075
    PC  5087
    PC  5086
    PC  5085
    PC  5084
    PC  5010
    PC  5012
    PC  5011
    PC  5014
    PC  5021
    PC  5020
Year: 2011
    PC  5000
    PC  5005
    PC  5006
    PC  5031
    PC  5033
    PC  5034
    PC  5061
    PC  5063
    PC  5065
    PC  5067
    PC  5069
    PC  5081
    PC  5083
    PC  5082
    PC  5007
    PC  5008
    PC  5009
    PC  5025
    PC  5032
    PC  5022
    PC  5023
    PC  5024
    PC  5037
    PC  5040
    PC  5045
    PC  5038
 

In [4]:
for i in range(3):
    while(len(database[i]) <= 52):
        database[i].append(0)
    print(len(database[i]))
db = np.zeros((53,3), np.int32)
db[:,0] = database[0]
db[:, 1] = database[1]
db[:, 2] = database[2]

53
53
53


In [5]:
print(db[0])
df = pd.DataFrame(db)
df.to_csv("adelaide_income2.csv")

[ 893  949 1093]
